 "use client";
import {useState} from "react"; import Link from "next/link"; import {demoIncident} from "../../lib/security";
type Result={level:"LEGITIMATE"|"REVIEW"|"UNAUTHORIZED";score:number;reasons:string[]};
function assess(newDevice:boolean,unknownLocation:boolean,failed:number):Result{
 let score=5,reasons:string[]=[];
 if(newDevice){score+=35;reasons.push("New device fingerprint");}
 if(unknownLocation){score+=40;reasons.push("Unrecognized sign-in location");}
 if(failed>0){score+=Math.min(20,failed*10);reasons.push(`${failed} failed sign-in attempt${failed>1?"s":""}`);}
 return score>=80?{level:"UNAUTHORIZED",score,reasons}:score>=40?{level:"REVIEW",score,reasons}:{level:"LEGITIMATE",score,reasons};
}
export default function Login(){const [user,setUser]=useState("");const [pass,setPass]=useState("");const [newDevice,setNew]=useState(false);const [unknown,setUnknown]=useState(false);const [failed,setFailed]=useState(0);const [result,setResult]=useState<Result|null>(null);
function signIn(e:React.FormEvent){e.preventDefault();const r=assess(newDevice,unknown,failed);
if(r.level==="LEGITIMATE"){window.location.href="/cyberbank";return;}
setResult(r);if(r.level!=="LEGITIMATE"){const i=demoIncident();i.risk=r.score;i.classification=r.level;i.reasons=r.reasons.length?r.reasons:i.reasons;i.timestamp=new Date().toISOString();localStorage.setItem("cyberbank_security_incident",JSON.stringify(i));localStorage.setItem("cyberbank_security_broadcast",Date.now().toString());}}
return <main className="min-h-screen bg-[#eef1f5]"><header className="border-b bg-white"><div className="mx-auto flex max-w-6xl justify-between px-6 py-4"><Link href="/cyberbank" className="text-xl font-bold text-[#123b63]">CYBERBANK</Link><span className="text-sm text-slate-500">Secure Online Banking</span></div></header><div className="mx-auto flex min-h-[calc(100vh-70px)] max-w-6xl items-center justify-center px-6"><div className="w-full max-w-md rounded-xl border bg-white p-8 shadow-soft"><div className="mb-7"><h1 className="text-2xl font-bold">Sign in</h1><p className="mt-2 text-sm text-slate-500">Enter your CyberBank demo credentials.</p></div><form onSubmit={signIn} className="space-y-4"><label className="block text-sm font-semibold">Customer ID<input value={user} onChange={e=>setUser(e.target.value)} className="mt-2 w-full rounded-lg border p-3 outline-none focus:border-blue-500" placeholder="krishna"/></label><label className="block text-sm font-semibold">Password<input value={pass} onChange={e=>setPass(e.target.value)} type="password" className="mt-2 w-full rounded-lg border p-3 outline-none focus:border-blue-500" placeholder="CyberBank@123"/></label><div className="space-y-2 rounded-lg bg-slate-50 p-4 text-sm"><div className="font-semibold">Demo security signals</div><label className="flex gap-2"><input type="checkbox" checked={newDevice} onChange={e=>setNew(e.target.checked)}/> New / unrecognized device</label><label className="flex gap-2"><input type="checkbox" checked={unknown} onChange={e=>setUnknown(e.target.checked)}/> Unrecognized location</label><label className="block">Previous failed attempts<select value={failed} onChange={e=>setFailed(Number(e.target.value))} className="ml-2 rounded border p-1"><option value="0">0</option><option value="1">1</option><option value="2">2</option></select></label></div><button className="w-full rounded-lg bg-[#123b63] py-3 font-semibold text-white">Sign in</button></form><p className="mt-5 text-center text-xs text-slate-400">Training simulation only • No real credentials are transmitted.</p></div></div>
{result&&result.level!=="LEGITIMATE"&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/70 p-5"><div className="w-full max-w-lg rounded-2xl bg-white shadow-2xl"><div className="border-b p-6"><div className="text-sm font-bold tracking-wide text-red-600">SECURITY ALERT</div><h2 className="mt-2 text-2xl font-bold text-slate-900">Unusual sign-in detected</h2><p className="mt-2 text-sm text-slate-600">CyberBank has automatically protected this session because the sign-in pattern requires security review.</p></div><div className="grid grid-cols-2 gap-3 p-6 text-sm"><div className="rounded-lg bg-slate-50 p-4"><span className="muted">Risk score</span><div className="mt-1 text-xl font-bold text-red-600">{result.score}/100</div></div><div className="rounded-lg bg-slate-50 p-4"><span className="muted">Classification</span><div className="mt-1 font-bold">{result.level}</div></div></div><div className="px-6 pb-5"><div className="text-sm font-semibold">Why this was flagged</div><ul className="mt-2 list-disc pl-5 text-sm text-slate-600">{result.reasons.map(x=><li key={x}>{x}</li>)}</ul></div><div className="flex gap-3 border-t p-6"><Link href="/bank-security" className="flex-1 rounded-lg bg-[#123b63] py-3 text-center text-sm font-semibold text-white">Open Security Operations</Link><button onClick={()=>setResult(null)} className="rounded-lg border px-5 py-3 text-sm font-semibold">Close</button></div></div></div>}</main>}